---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kibana
  labels:
    name: kibana
spec:
  serviceName: kibana
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: kibana
      labels:
        name: kibana
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: default
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5601
          resources:
            requests:
              cpu: 0.3
              memory: 500Mi
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch-service:9200
            - name: XPACK_MONITORING_ENABLED
              value: "false"
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  annotations:
    # ensure the client ip is propagated to avoid the invalid crumb issue (k8s <1.7)
    # service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  type: NodePort
  selector:
    name: kibana
  # k8s 1.7+
  externalTrafficPolicy: Local
  ports:
    -
      name: http
      port: 5601
      targetPort: 5601
      protocol: TCP
